goal_distance_from_table: 0.6

shooter_valve_on_duration:
  dual_table_lower_shooter      : 0.5
  dual_table_upper_left_shooter : 0.5
  dual_table_upper_right_shooter: 0.5
  movable_table_1200_shooter    : 0.5
  movable_table_1500_shooter    : 0.5
  movable_table_1800_shooter    : 0.5