table_position:
  dual_table        : [2.5, 2.4]
  movable_table_1200: [4.5, 1.9]
  movable_table_1500: [5.5, 1.4]
  movable_table_1800: [6.5, 2.4]

goal_distance_from_table_base_face: 0.6

hough_min_line_length: 0.375
hough_max_line_gap: 0.05

table_base_face_center_error_tolerance: 0.25