obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    topic: lidar/scan
    sensor_frame: lidar_link
    data_type: LaserScan
    clearing: true
    marking: true
    obstacle_range: 7.5
    raytrace_range: 10.0
    inf_is_valid: true

robot_base_frame: base_link

footprint: [[425.0e-3, 425.0e-3], [-425.0e-3, 425.0e-3], [-425.0e-3, -425.0e-3], [425.0e-3, -425.0e-3]]