global_costmap:
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  global_frame     : map

  update_frequency : 1.0
  publish_frequency: 1.0

  static_layer:
    map_topic: map
    track_unknown_space: true

  inflation_layer:
    inflation_radius: 0.5