local_costmap:
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  global_frame     : odom

  update_frequency : 5.0
  publish_frequency: 2.0

  rolling_window: true
  width         : 5
  height        : 5
  resolution    : 0.1

  # inflation_layer:
  #   inflation_radius: 0.2