base_global_planner      : global_planner/GlobalPlanner
base_local_planner       : teb_local_planner/TebLocalPlannerROS

planner_frequency        : 0.0
controller_frequency     : 5.0

recovery_behavior_enabled: false

GlobalPlanner:
  orientation_mode: 2 # interpolate